[beegfs_mgmtd]
nodeA ansible_host=172.24.14.40
[beegfs_meta]
nodeA

[beegfs_storage]
nodeA
nodeB ansible_host=172.24.14.41

[beegfs_client]
nodeA
nodeB

# Суперgroup: все узлы BeeGFS
[beegfs:children]
beegfs_mgmtd
beegfs_meta
beegfs_storage
beegfs_client

[beegfs:vars]
ansible_user=admin
ansible_become=true
ansible_ssh_private_key_file=/home/thinkpad/.ssh/beegfs
