---
# Storage node ID и target ID для nodeB (из лабы: -s 2 -i 201)
beegfs_storage_node_id: 2
beegfs_storage_target_id: 201

# Диск для storage target.
# Terraform подключает диск через virtio_scsi — он всегда виден как /dev/sdb.
# Если топология отличается, проверьте через lsblk после первого старта ВМ.
beegfs_storage_device: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3af47b46-ecbf-41f3-9a1c-58d6475598a8"
